development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Sangwapo_virtual_development
  pool: 5
  username: sangwapo
  password: VirtualSangwapoPassword
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Sangwapo_virtual_test
  pool: 5
  username: sangwapo
  password: VirtualSangwapoPassword
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: Sangwapo_virtual
  pool: 5
  username: sangwapo
  password: VirtualSangwapoPassword
  host: localhost
