defaults: &defaults
  http_basic_name: preview
  http_basic_password: future
  test_user_password: virtual

  application_name: "Sangwapo"
  gemset_name: "sangwapo-rails.3.2.x"
  ruby_version: ruby-2.0.0-p247
  user: deploy

  miniumum_version_of_bundler: ">=1.3.5"
  miniumum_version_of_rake: ">=10.1.0"


  # Multi-stage recipe settings
  # Virtual deployment
  virtual_deployment_path: virtual
  virtual_repository_deployment_branch: master
  virtual_server_name: sangwapo.virtual
  virtual_stage_name: virtual

  # Staging deployment
  server_name_staging: sangwapo.clientcase.net
  deployment_path_staging: staging
  stage_name_staging: staging

  # Production deployment
  server_name_production: sangwapo.com
  deployment_path_production: production
  stage_name_production: production




  # Email settings
  email_address: "lacalhost"
  email_domain: ""
  email_password: "" # Update this in production
  email_port: 25
  email_user_name: "hello@sangwapo.com"

  # ActionMailer settings
  application_server_name: "sangwapo.virtual"

  # Mobile "gateway"
  application_sim_cards:
    airtel:
      "0970000000": "0970000000"
      "0970000001": "0970000001"
      "0970000002": "0970000002"
    mtn:
      "0960000000": "0960000000"
      "0960000001": "0960000001"
      "0960000002": "0960000002"
    zamtel:
      "0950000000": "0950000000"
      "0950000001": "0950000001"
      "0950000002": "0950000002"

  # Business rules
  refund_percentage: 80

  # Public contact information
  public_contact_email_address: hello@sangwapo.com

development:
  <<: *defaults

  server_name: "0.0.0.0:3002"

test:
  <<: *defaults

production:
  <<: *defaults

  # Mobile "gateway"
  application_sim_cards:
    airtel:
      "0971746967": "0971746967"
    mtn:
      "0969126829": "0969126829"
    zamtel:
      "0950930425": "0950930425"
