defaults: &defaults
  http_basic_name: preview
  http_basic_password: future
  test_user_password: password

  # Deployment recipe settings
  application_name: "Sangwapo"
  deployment_branch: "deployment"
  gemset_name: "sangwapo-rails.3.1.x"
  ruby_version: "ruby-1.9.3-p0"
  server_name: "sangwapo.com"
  user: "silumesii"
  
  # Email settings
  email_address: "smtp.gmail.com"
  email_domain: "gmail.com"
  email_password: "password" # Update this in production
  email_port: 587
  email_user_name: "hello@sangwapo.com"
  
  # Mobile "gateway"
  application_sim_cards:
    airtel:
      "0970000000": "0970000000"
      "0970000001": "0970000001"
      "0970000002": "0970000002"
    mtn:
      "0960000000": "0960000000"
      "0960000001": "0960000001"
      "0960000002": "0960000002"
    zamtel:
      "0950000000": "0950000000"
      "0950000001": "0950000001"
      "0950000002": "0950000002"
      
  # Business rules
  refund_percentage: 80

development:
  <<: *defaults

  server_name: "0.0.0.0:3002"

test:
  <<: *defaults

production:
  <<: *defaults

  # Mobile "gateway"
  application_sim_cards:
    airtel:
      "0970000000": "0970000000"
    mtn:
      "0960000000": "0960000000"
    zamtel:
      "0950000000": "0950000000"
